#!/bin/sh
echo -e "List of all real users in the system\n"
cat /etc/passwd | awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}'

echo -e "\nEnter username that you want to delete:"
read USERNAME

USER = $(/etc/passwd | awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' | grep "$USERNAME")

if [-n $USER]
    then
        echo -e "Deleting in process\n"
        sudo killall -u $USER
        sudo userdel -rf $USER
        echo -e "\n$USER deleted."
    else
        echo -e "\n$USER not in the system."
fi