#!/bin/sh
echo "List of all real users in the system"
cat /etc/passwd | awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}'

echo "Enter username that you want to delete:"
read USERNAME

USER=$(cat /etc/passwd | awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' | grep "$USERNAME")

if [ -n "$USER" ]
    then
        sudo userdel -rf $USER
        echo "$USER deleted."
    else
        echo "User not found in the system."
fi